import { StyleSheet } from "react-native";
import { colors, layout, spacing, typography } from "../../constants/theme";

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: colors.background.darkGreen,
  },
  topImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    minHeight: 250,
  },
  closeButton: {
    width: layout.icon.sm,
    height: layout.icon.sm,
    borderRadius: layout.icon.sm / 2,
    backgroundColor: colors.overlay.dark,
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: spacing.xl + 1,
    right: spacing.xl + 1,
    zIndex: 10,
  },
  closeText: {
    color: colors.text.white,
    fontSize: typography.size.xl,
    textAlign: "center",
    fontWeight: "400",
  },
  content: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.xxl,
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },
  title: {
    fontSize: typography.size.huge,
    color: colors.text.white,
    fontFamily: typography.fonts.Rubik,
    marginTop: 0,
    marginBottom: spacing.xs,
    textAlign: "left",
  },
  titleBold: {
    fontFamily: typography.fonts.RubikExtraBold,
    color: colors.text.white,
  },
  subtitle: {
    fontSize: typography.size.xlg,
    color: colors.text.lightWhite,
    fontFamily: typography.fonts.RubikLight,
    marginBottom: spacing.xxl,
    textAlign: "center",
  },
  featuresRow: {
    padding: 0,
    margin: 0,
    maxHeight: 130,
    marginBottom: spacing.xxl,
  },
  marginLeft: {
    marginLeft: spacing.sm,
  },
  featureCard: {
    width: 156,
    backgroundColor: colors.overlay.white,
    borderRadius: layout.radius.xl,
    padding: spacing.md,
    height: 130,
    marginRight: spacing.sm,
  },
  featureIcon: {
    width: layout.icon.md,
    height: layout.icon.md,
    borderRadius: layout.radius.md,
    backgroundColor: "#1D2B23",
    marginBottom: spacing.lg,
    alignItems: "center",
    justifyContent: "center",
  },
  featureIconImage: {
    width: layout.icon.md,
    height: 35.68,
    marginBottom: spacing.xxl,
  },
  featureTitle: {
    fontSize: typography.size.xxl,
    fontFamily: typography.fonts.RubikMedium,
    color: colors.text.white,
    marginBottom: spacing.xs,
  },
  featureDesc: {
    fontSize: typography.size.base,
    fontFamily: typography.fonts.RubikRegular,
    color: colors.text.lightWhite,
  },
  planBox: {
    width: "100%",
    borderRadius: layout.radius.xxl,
    borderWidth: 1,
    borderColor: colors.border.white,
    backgroundColor: colors.overlay.white,
    marginBottom: spacing.md + 2,
    padding: spacing.lg,
  },
  planBoxActive: {
    borderColor: colors.primary.green,
    backgroundColor: colors.overlay.green,
    marginBottom: spacing.xxl,
  },
  planRow: {
    flexDirection: "row",
    position: "relative",
    alignItems: "center",
  },
  radioCircle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.text.white,
  },
  radio: {
    width: layout.icon.sm,
    height: layout.icon.sm,
    borderRadius: 11,
    backgroundColor: colors.overlay.white,
    marginRight: spacing.md,
  },
  radioActive: {
    borderColor: colors.primary.green,
    backgroundColor: colors.primary.green,
    justifyContent: "center",
    alignItems: "center",
  },
  planTextBox: {
    flex: 1,
  },
  planTitle: {
    color: colors.text.white,
    fontFamily: typography.fonts.RubikMedium,
    fontSize: typography.size.lg,
    marginBottom: spacing.xs - 2,
  },
  planDesc: {
    color: colors.text.lightWhite,
    fontSize: typography.size.base,
    fontFamily: typography.fonts.RubikRegular,
  },
  planDescDim: {
    fontSize: typography.size.base,
    fontFamily: typography.fonts.RubikMedium,
  },
  saveBadge: {
    position: "absolute",
    height: 26,
    top: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.primary.green,
    borderBottomStartRadius: 18,
    borderTopRightRadius: layout.radius.lg,
    paddingHorizontal: spacing.sm + 2,
    paddingVertical: spacing.xs - 2,
  },
  saveBadgeText: {
    color: colors.text.white,
    fontWeight: "700",
    fontSize: typography.size.base,
  },
  legalText: {
    color: colors.overlay.darkTransparent,
    fontSize: typography.size.xs,
    textAlign: "center",
    marginTop: spacing.sm,
    marginBottom: spacing.md,
  },
  linksRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  link: {
    color: colors.overlay.darkTransparent,
    fontSize: typography.size.sm,
    fontWeight: "500",
    marginHorizontal: spacing.xs + 2,
    textDecorationLine: "underline",
  },
  linkDot: {
    color: colors.overlay.darkTransparent,
    fontSize: typography.size.sm,
    fontWeight: "500",
    marginHorizontal: 0,
  },
});
