import { StyleSheet, Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#101E17",
  },
  topImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    minHeight: 250,
  },
  closeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 25,
    right: 25,
    zIndex: 10,
  },
  closeText: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "400",
  },
  content: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 32,
    color: "#fff",
    fontWeight: "400",
    marginTop: 0,
    marginBottom: 4,
    textAlign: "left",
  },
  titleBold: {
    fontWeight: "700",
    color: "#fff",
  },
  subtitle: {
    fontSize: 18,
    color: "#B6C2B7",
    fontWeight: "400",
    marginBottom: 24,
    textAlign: "center",
  },
  featuresRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
    marginBottom: 28,
  },
  featureCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.06)",
    borderRadius: 20,
    marginHorizontal: 6,
    alignItems: "center",
    paddingVertical: 18,
    paddingHorizontal: 8,
  },
  featureIcon: {
    width: 32,
    height: 32,
    backgroundColor: "rgba(255,255,255,0.12)",
    borderRadius: 8,
    marginBottom: 10,
  },
  featureTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 2,
  },
  featureDesc: {
    color: "#B6C2B7",
    fontSize: 13,
    fontWeight: "400",
  },
  planBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    backgroundColor: "rgba(255,255,255,0.04)",
    marginBottom: 14,
    padding: 16,
  },
  planBoxActive: {
    borderColor: "#28AF6E",
    backgroundColor: "rgba(40,175,110,0.08)",
  },
  planRow: {
    flexDirection: "row",
    position: "relative",
    alignItems: "center",
  },
  radio: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "#B6C2B7",
    marginRight: 14,
    backgroundColor: "transparent",
  },
  radioActive: {
    borderColor: "#28AF6E",
    backgroundColor: "#28AF6E",
  },
  planTextBox: {
    flex: 1,
  },
  planTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 2,
  },
  planDesc: {
    color: "#B6C2B7",
    fontSize: 13,
    fontWeight: "400",
  },
  planDescDim: {
    color: "#6A7B6E",
    fontSize: 13,
    fontWeight: "400",
  },
  saveBadge: {
    position: "absolute",
    height: 26,
    top: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#28AF6E",
    borderBottomStartRadius: 12,
    borderTopRightRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  saveBadgeText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  legalText: {
    color: "#B6C2B7",
    fontSize: 12,
    textAlign: "center",
    marginTop: 18,
    marginBottom: 10,
  },
  linksRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 2,
  },
  link: {
    color: "#B6C2B7",
    fontSize: 14,
    fontWeight: "500",
    marginHorizontal: 6,
    textDecorationLine: "underline",
  },
  linkDot: {
    color: "#B6C2B7",
    fontSize: 14,
    fontWeight: "500",
    marginHorizontal: 0,
  },
});

export default styles;
