import { StyleSheet } from "react-native";

export default StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#101E17",
  },
  topImage: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "100%",
    justifyContent: "flex-start",
    alignItems: "flex-end",
    minHeight: 250,
  },
  closeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "rgba(0,0,0,0.4)",
    alignItems: "center",
    justifyContent: "center",
    position: "absolute",
    top: 25,
    right: 25,
    zIndex: 10,
  },
  closeText: {
    color: "#fff",
    fontSize: 18,
    textAlign: "center",
    fontWeight: "400",
  },
  content: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "flex-start",
  },
  title: {
    fontSize: 32,
    color: "#fff",
    fontWeight: "400",
    marginTop: 0,
    marginBottom: 4,
    textAlign: "left",
  },
  titleBold: {
    fontWeight: "700",
    color: "#fff",
  },
  subtitle: {
    fontSize: 18,
    color: "#B6C2B7",
    fontWeight: "400",
    marginBottom: 24,
    textAlign: "center",
  },
  featuresRow: {
    padding: 0,
    margin: 0,
    maxHeight: 130,
    marginBottom: 24,
  },
  marginLeft: {
    marginLeft: 8,
  },
  featureCard: {
    width: 156,
    backgroundColor: "rgba(255, 255, 255, 0.08)",
    borderRadius: 14,
    padding: 16,
    height: 130,
  },
  featureIcon: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: "#1D2B23",
    marginBottom: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  featureIconImage: {
    width: 24,
    height: 24,
  },
  featureTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#fff",
    marginBottom: 4,
  },
  featureDesc: {
    fontSize: 13,
    color: "rgba(255, 255, 255, 0.7)",
  },
  planBox: {
    width: "100%",
    borderRadius: 16,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
    backgroundColor: "rgba(255,255,255,0.05)",
    marginBottom: 14,
    padding: 16,
  },
  planBoxActive: {
    borderColor: "#28AF6E",
    backgroundColor: "rgba(40,175,110,0.08)",
    marginBottom: 24,
  },
  planRow: {
    flexDirection: "row",
    position: "relative",
    alignItems: "center",
  },
  radioCircle: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#fff",
  },
  radio: {
    width: 24,
    height: 24,
    borderRadius: 11,
    backgroundColor: "rgba(255,255,255,0.08)",
    marginRight: 12,
  },
  radioActive: {
    borderColor: "#28AF6E",
    backgroundColor: "#28AF6E",
    justifyContent: "center",
    alignItems: "center",
  },
  planTextBox: {
    flex: 1,
  },
  planTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 16,
    marginBottom: 2,
  },
  planDesc: {
    color: "#B6C2B7",
    fontSize: 13,
    fontWeight: "400",
  },
  planDescDim: {
    color: "#6A7B6E",
    fontSize: 13,
    fontWeight: "400",
  },
  saveBadge: {
    position: "absolute",
    height: 26,
    top: 0,
    right: 0,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#28AF6E",
    borderBottomStartRadius: 18,
    borderTopRightRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 2,
  },
  saveBadgeText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 13,
  },
  legalText: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 9,
    textAlign: "center",
    marginTop: 8,
    marginBottom: 12,
  },
  linksRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  link: {
    color: "rgba(255,255,255,0.52)",

    fontSize: 11,
    fontWeight: "500",
    marginHorizontal: 6,
    textDecorationLine: "underline",
  },
  linkDot: {
    color: "rgba(255,255,255,0.52)",

    fontSize: 11,
    fontWeight: "500",
    marginHorizontal: 0,
  },
});
